title: DfE Digital Technical Guidance

permalink: pretty

defaults:
  -
    scope:
      path: "standards"
    values:
      standard: true
  -
    scope:
      path: "guides"
    values:
      guide: true
  -
    scope:
      path: "principles"
    values:
      principle: true
